from __future__ import annotations

import importlib
from pathlib import Path

import pandas as pd

from src.paper.config import APPENDIX_TABLES, BuildContext
from src.paper.figures.real_builders import build_figure


def _context(tmp_path: Path) -> BuildContext:
    return BuildContext(
        root=Path(__file__).resolve().parents[1],
        outputs=tmp_path / "paper_outputs",
        docs=tmp_path / "paper_docs",
    )


def _ensure_dirs(context: BuildContext) -> None:
    for subdir in ["tables", "appendix", "figures", "manifests", "memos", "latex"]:
        (context.outputs / subdir).mkdir(parents=True, exist_ok=True)
    context.docs.mkdir(parents=True, exist_ok=True)


def test_appendix_tables_are_data_driven(tmp_path):
    context = _context(tmp_path)
    _ensure_dirs(context)

    for name in APPENDIX_TABLES:
        mod = importlib.import_module(f"src.paper.appendix.{name}")
        result = mod.build(context)
        table = pd.read_csv(result["csv"])
        assert "module" not in table.columns, name
        assert "Mapped from existing repository module" not in table.to_string(), name

    portability = pd.read_csv(context.outputs / "appendix" / "tableA13_portability.csv")
    assert "captain-group holdout" in set(portability.get("test", []))
    assert "agent-group holdout" in set(portability.get("test", []))

    matching = pd.read_csv(context.outputs / "appendix" / "tableA15_matching_robustness.csv")
    assert "bootstrap_se" in matching.columns
    assert matching["row_label"].fillna("").str.contains("bootstrap").any()


def test_figures_are_not_placeholders(tmp_path):
    context = _context(tmp_path)
    _ensure_dirs(context)

    for name in ["fig01_sample_flow", "fig05_switch_event_study", "fig10_matching_welfare"]:
        result = build_figure(name, context)
        assert Path(result["figure"]).exists(), name
        memo = Path(result["memo"]).read_text(encoding="utf-8")
        assert "Placeholder figure generated by paper layer." not in memo, name
