"""
Phase 0: Sample and Variable Audit.

Builds a voyage-level manifest with flags for which tables each
observation appears in, and records exact variable definitions.
"""

import numpy as np
import pandas as pd
from pathlib import Path

from .utils.io import (
    DATA_DIR, MANIFESTS_DIR, ensure_dirs, write_table, write_doc,
)
from .utils.checks import compute_descriptive_stats


def _load_raw_voyage() -> pd.DataFrame:
    """Load the raw voyage parquet."""
    path = DATA_DIR / "analysis_voyage.parquet"
    df = pd.read_parquet(path)
    # Canonical ID renaming (mirrors data_loader.py)
    for name_col, id_col in [
        ("captain_name_clean", "captain_id"),
        ("agent_name_clean", "agent_id"),
        ("vessel_name_clean", "vessel_id"),
    ]:
        if id_col not in df.columns and name_col in df.columns:
            df = df.rename(columns={name_col: id_col})
    return df


def _apply_base_filters(df: pd.DataFrame) -> pd.DataFrame:
    """Apply the standard analysis filters (mirrors data_loader.py)."""
    df = df[df["year_out"].notna()].copy()
    df["year_out"] = df["year_out"].astype(int)
    df = df[(df["year_out"] >= 1780) & (df["year_out"] <= 1930)]
    df = df[df["captain_id"].notna() & df["agent_id"].notna()]
    df = df[df["q_total_index"] > 0]
    df["log_q"] = np.log(df["q_total_index"])
    # Trim outliers at 0.5% / 99.5%
    lo = df["log_q"].quantile(0.005)
    hi = df["log_q"].quantile(0.995)
    df = df[(df["log_q"] >= lo) & (df["log_q"] <= hi)]
    return df


def _get_connected_set(df: pd.DataFrame) -> pd.DataFrame:
    """Get LOO connected set using existing code."""
    try:
        from src.analyses.run_full_baseline_loo_eb import get_loo_connected_set
        df_loo, diag = get_loo_connected_set(df)
        return df_loo
    except Exception as e:
        print(f"  ⚠ Could not compute LOO connected set: {e}")
        print("    Falling back to simple connected-component set")
        import networkx as nx
        G = nx.Graph()
        for _, row in df[["captain_id", "agent_id"]].iterrows():
            G.add_edge(f"c_{row['captain_id']}", f"a_{row['agent_id']}")
        largest_cc = max(nx.connected_components(G), key=len)
        cc_captains = {n[2:] for n in largest_cc if n.startswith("c_")}
        cc_agents = {n[2:] for n in largest_cc if n.startswith("a_")}
        return df[
            df["captain_id"].isin(cc_captains) & df["agent_id"].isin(cc_agents)
        ].copy()


def run_manifests() -> dict:
    """
    Build the sample manifest and variable documentation.

    Returns
    -------
    dict with keys: manifest_df, table1_sample, connected_set_sample
    """
    print("\n" + "=" * 70)
    print("PHASE 0: SAMPLE AND VARIABLE AUDIT")
    print("=" * 70)
    ensure_dirs()

    # --- Load and filter ---
    df_raw = _load_raw_voyage()
    print(f"  Raw data: {len(df_raw):,} voyages")

    df_filtered = _apply_base_filters(df_raw)
    print(f"  After base filters: {len(df_filtered):,} voyages")

    # --- Connected set ---
    df_connected = _get_connected_set(df_filtered)
    print(f"  Connected set: {len(df_connected):,} voyages")
    print(f"    Captains: {df_connected['captain_id'].nunique():,}")
    print(f"    Agents: {df_connected['agent_id'].nunique():,}")

    # --- Table flags ---
    # Table 1: descriptive stats — uses the full filtered sample
    table1_ids = set(df_filtered["voyage_id"])

    # Table 2: entropy table — needs ground_or_route
    has_ground = df_filtered["ground_or_route"].notna()
    table2_ids = set(df_filtered.loc[has_ground, "voyage_id"])

    # Table 3: variance decomposition — uses connected set
    table3_ids = set(df_connected["voyage_id"])

    # Table A6: stopping rule — needs logbook positions (flag conceptual)
    # We'll flag voyages that have route data as a proxy
    has_route_data = df_filtered.get("has_route_data", pd.Series(False, index=df_filtered.index))
    tableA6_ids = set(df_filtered.loc[has_route_data == True, "voyage_id"]) if has_route_data.any() else set()

    # Lay data: confirmed absent
    manifest = df_filtered[["voyage_id", "captain_id", "agent_id",
                             "home_port", "year_out"]].copy()
    manifest["in_table1_sample"] = manifest["voyage_id"].isin(table1_ids)
    manifest["in_table2_sample"] = manifest["voyage_id"].isin(table2_ids)
    manifest["in_table3_sample"] = manifest["voyage_id"].isin(table3_ids)
    manifest["in_tableA6_sample"] = manifest["voyage_id"].isin(tableA6_ids)
    manifest["has_lay_data"] = False

    # Save manifest
    manifest_path = MANIFESTS_DIR / "sample_manifest.parquet"
    manifest.to_parquet(manifest_path, index=False)
    print(f"\n  → Wrote sample_manifest.parquet ({len(manifest):,} rows)")

    # --- Variable definitions doc ---
    var_defs = f"""# Sample Manifest — Variable Definitions

*Generated by Phase 0 of the minor-revision patch.*

## Sample Sizes

| Sample | N voyages | N captains | N agents |
|--------|-----------|------------|----------|
| Raw data | {len(df_raw):,} | {df_raw['captain_id'].nunique():,} | {df_raw['agent_id'].nunique():,} |
| After base filters | {len(df_filtered):,} | {df_filtered['captain_id'].nunique():,} | {df_filtered['agent_id'].nunique():,} |
| Connected set (Table 3) | {len(df_connected):,} | {df_connected['captain_id'].nunique():,} | {df_connected['agent_id'].nunique():,} |
| Has ground_or_route (Table 2) | {has_ground.sum():,} | — | — |
| Has route data (Table A6 proxy) | {len(tableA6_ids):,} | — | — |
| Has lay data | 0 | — | — |

## Variable Definitions

| Variable | Definition | Source |
|----------|------------|--------|
| `voyage_id` | Unique voyage identifier | `analysis_voyage.parquet` |
| `captain_id` | Captain identity (cleaned name) | Derived from `captain_name_clean` |
| `agent_id` | Managing agent identity (cleaned name) | Derived from `agent_name_clean` |
| `home_port` | Home port of departure | `analysis_voyage.parquet` |
| `ground_or_route` | Whaling ground / destination route | 642 unique values, 58% coverage |
| `log_q` | Log total oil output: `ln(q_total_index)` | Constructed; trimmed at 0.5%/99.5% |
| `q_total_index` | Total oil output (sperm + whale oil barrel-equivalent index) | `analysis_voyage.parquet` |
| `tonnage` | Vessel tonnage | 41% coverage |
| `duration_days` | Voyage duration in days | 81% coverage |
| `captain_lay` | Captain's lay fraction | **NOT AVAILABLE** |
| `mate_lay` | First mate's lay fraction | **NOT AVAILABLE** |

## Sample Flags

| Flag | Meaning |
|------|---------|
| `in_table1_sample` | Included in Table 1 descriptive statistics |
| `in_table2_sample` | Has non-null `ground_or_route` for Table 2 entropy analysis |
| `in_table3_sample` | In the LOO connected set for Table 3 AKM decomposition |
| `in_tableA6_sample` | Has route tracking data (proxy for logbook positions) |
| `has_lay_data` | Has lay/incentive contract data (always False) |
"""
    write_doc("sample_manifest.md", var_defs)

    # Summary stats for key outcome
    stats_t1 = compute_descriptive_stats(df_filtered["log_q"].values, "Table 1 log_q")
    stats_t3 = compute_descriptive_stats(df_connected["log_q"].values, "Table 3 log_q (connected set)")

    return {
        "manifest_df": manifest,
        "df_filtered": df_filtered,
        "df_connected": df_connected,
        "stats_table1": stats_t1,
        "stats_table3": stats_t3,
    }
