"""
Phase 5: Rebuild only the impacted paper artifacts.

Produces final versions of revised tables and figures
without reopening unrelated sections.
"""

import pandas as pd

from .utils.io import write_table, write_memo, ensure_dirs


def run_rebuild_impacted(
    table2_results: dict,
    stopping_results: dict,
    lay_results: dict,
    scale_results: dict,
) -> None:
    """
    Rebuild only the paper artifacts touched by the four fixes.
    """
    print("\n" + "=" * 70)
    print("PHASE 5: REBUILD IMPACTED PAPER ARTIFACTS")
    print("=" * 70)
    ensure_dirs()

    # --- Final Table 2 for paper ---
    if "table2a" in table2_results and table2_results["table2a"] is not None:
        write_table(
            table2_results["table2a"],
            "final_table2_for_paper",
            caption="Table 2: Route-Choice Information Attribution (Revised)",
            notes=(
                "Replaces the raw in-sample Shannon routing table with "
                "degree-of-freedom-penalized metrics. AMI adjusts for chance "
                "agreement. Bootstrap CIs via captain-level block resampling."
            ),
        )
        print("  ✓ Final Table 2 written")

    # --- Final Table 1 (corrected) ---
    if "corrected_t1" in scale_results:
        write_table(
            scale_results["corrected_t1"],
            "final_table1_for_paper",
            caption="Table 1: Descriptive Statistics (Corrected)",
            notes=(
                "Live-computed from the analysis sample. "
                "Connected-set statistics reported separately."
            ),
        )
        print("  ✓ Final Table 1 (corrected) written")

    # --- Paper patch summary memo ---
    memo_lines = [
        "# Paper Patch Summary\n",
        "*Generated by the minor-revision pipeline.*\n",
        "## Changes Made\n",
        "### 1. Table 2: Route-Choice Information (REVISED)",
        "- Replaced raw Shannon entropy / MI with AMI, conditional MI, and OOS prediction.",
        "- Added Table 2A (AMI), 2B (conditional MI), 2C (frequency robustness), 2D (OOS prediction).",
        "- Interpretation updated: metrics now clearly distinguish descriptive MI from ",
        "  adjusted AMI and incremental conditional MI.\n",
        "### 2. Appendix Figure A13: Stopping Threshold Curve (NEW)",
        "- Added coefficient path across percentile cutoffs (5th–50th).",
        "- Panel A: OLS coefficient + 95% CI.",
        "- Panel B: Share/count of patches classified empty.",
    ]

    if stopping_results and stopping_results.get("aft_results") is not None:
        memo_lines.append("- Panel C: AFT Weibull coefficient path.\n")
    else:
        memo_lines.append("- Panel C: AFT Weibull (not available).\n")

    memo_lines.extend([
        "### 3. Lay-System Note (NEW APPENDIX)",
        "- Coverage audit: no lay variables in dataset.",
        "- Institutional evidence documented (standardized lay shares).",
    ])

    if lay_results.get("proxy_results") is not None:
        memo_lines.append("- Vessel-type proxy test included.\n")
    else:
        memo_lines.append("- No proxy variables available for regression test.\n")

    memo_lines.extend([
        "### 4. Table 1 / Table 3 Scale (CORRECTED)",
        f"- Discrepancy: {scale_results.get('discrepancy_note', 'See scale_audit_fix.md')}",
        "- Table 1 now live-computed from data.",
        "- Table 3 notes updated with connected-set sample stats.\n",
        "## Tables NOT Reopened",
        "- Table 4: mover design for search geometry ✓ PRESERVED",
        "- Table 5: sparse/rich interaction (θ × ψ) ✓ PRESERVED",
        "- Table 6: CATE by captain quartile ✓ PRESERVED",
        "- Table 7: sparse/rich matching counterfactual ✓ PRESERVED",
        "- Table A9: mate-to-captain mechanism ✓ PRESERVED",
    ])

    write_memo("paper_patch_summary.md", "\n".join(memo_lines))
    print("  ✓ Paper patch summary memo written")
